-- SQL SCHEMA FOR SUPABASE REALTIME NOTIFICATIONS
-- Run this script in the Supabase SQL Editor to set up the notification table and enable Realtime streaming.

-- 1. Create the 'manga_updates' table
CREATE TABLE IF NOT EXISTS public.manga_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manga_id TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    chapter_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
-- For development/testing, you can enable public select, or disable RLS:
ALTER TABLE public.manga_updates ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read updates
CREATE POLICY "Allow public read access" 
ON public.manga_updates 
FOR SELECT 
USING (true);

-- Only authenticated services/admin should insert (optional, customise as needed)
CREATE POLICY "Allow service insert" 
ON public.manga_updates 
FOR INSERT 
WITH CHECK (true);

 -- 3. Enable Supabase Realtime for 'manga_updates'
    alter publication supabase_realtime add table public.manga_updates;

-- 4. Table to store user device push tokens for Expo Push Notifications
CREATE TABLE IF NOT EXISTS public.user_push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    push_token TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table to store known mangas on the server for update checks
CREATE TABLE IF NOT EXISTS public.supabase_known_mangas (
    manga_id TEXT PRIMARY KEY,
    latest_chapter_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for new tables
ALTER TABLE public.user_push_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supabase_known_mangas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert/select on tokens" 
ON public.user_push_tokens 
FOR ALL 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow public select on server known mangas" 
ON public.supabase_known_mangas 
FOR ALL 
USING (true)
WITH CHECK (true);

-- 6. Sample Insert to test Realtime
-- INSERT INTO public.manga_updates (manga_id, title, body, chapter_id)
-- VALUES ('solo-leveling', 'Update Chapter Baru! ⚡', 'Chapter 180 untuk Solo Leveling telah rilis!', 'ch-180');

-- 7. Deploying Deno Edge Function using Supabase CLI:
-- Open your terminal and run:
-- supabase functions deploy check-updates --project-ref xszxixizrfmxkxfbczfr
--
-- 8. Scheduling the Edge Function with pg_cron & pg_net:
-- Run this in your Supabase SQL Editor to schedule the checks every 15 minutes:
--
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- CREATE EXTENSION IF NOT EXISTS pg_net;
--
-- SELECT cron.schedule(
--   'check-manga-updates-cron',
--   '*/15 * * * *', 
--   $$
--   SELECT net.http_post(
--     'https://xszxixizrfmxkxfbczfr.supabase.co/functions/v1/check-updates',
--     '{}',
--     'application/json',
--     '{"Authorization": "Bearer YOUR_ANON_KEY_HERE"}'
--   );
--   $$
-- );

